services:
  clickhouse:
    image: clickhouse/clickhouse-server
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    restart: unless-stopped

volumes:
  clickhouse_data:

